### ISSUE TITLE
Add new CiviCRM external routes

### ISSUE THREAD

**Issue by bjendres** [systopia/CiviProxy#44]
With CiviCRM ``5.27+`` CiviCRM offers new external routes, see [CORE-17312](https://github.com/civicrm/civicrm-core/pull/17312).

@seamuslee001 has created PR #43 for that.

**Comment by pbatroff** [comment]
CiviCRM uses the new routes per default, so when upgrading CiviCRM and *not* upgrading the extension, link replacement will fail. To allow continuous functionality I would advice to set `prefer standalone script` in `/civicrm/admin/setting/url`

**Comment by nalonsopress** [comment]
It looks like Civicrm adds crm?civiwp=CiviCRM which will break the replacements for WordPress even when upgrading the extension.

**Comment by bjendres** [comment]
Thanks for reporting @nalonsopress. We don't really use WordPress atm so a PR would be appreciated. And maybe a separate ticket would be helpful to others, too.

**Comment by pbatroff** [comment]
Open tracking with newer Mosaico Version uses the qid paramter instead of q. This can be replaced in open.php (https://github.com/systopia/CiviProxy/blob/ecc6eebfb09a8de0089257f66a889662e275fbd3/proxy/open.php#L20) by simply change the accepted parameters to qid as well.

tested with Mosaico 2.8

**Comment by pbatroff** [comment]
I would propose https://github.com/systopia/CiviProxy/commit/61f25b53f21790507812434b026d82c25b74b859 (issues/44 branch) for this. I tested this with Mosaico 2.8.

I also checked Mailings from various installations, and all seem to use qid as a parameter now.
