### ISSUE TITLE
Extension does not support -dev release

### ISSUE THREAD

**Issue by codebymikey** [systopia/CiviProxy#46]
The regex at https://github.com/systopia/CiviProxy/blob/bbf5c3c9e9c0b3d8e453cc2139d0ab17d84dba59/de.systopia.civiproxy/CRM/Admin/Form/Setting/ProxySettings.php#L108-L113 does not match dev releases such as "CiviProxy Version 0.6-dev" which is the current latest version.

**Comment by bjendres** [comment]
That's a good point. @codebymikey Care to provide a PR?

**Comment by codebymikey** [comment]
Made a PR, the regex could be simplified to `(([0-9]+(\.[0-9]+){1,2})(?:-[0-9A-Za-z-]+)?)`, but that's up to you.
