### ISSUE TITLE
compatibility: does civiproxy work with drupal9 and civicrm 7.60?

### ISSUE THREAD

**Issue by jankowa** [systopia/CiviProxy#65]
I just upgraded and migrated an older civicrm installation from drupal7 to drupal9 and tried to reenable civiproxy.

While debugging I wan't to be sure that I can expect that civiproxy is still compatible with drupal9 / civicrm 7.60.

Actually I try to get working the features mailinglist subscription and url. For the latter: Instead of passing the content through the proxy it just redirects to the correct target civicrm url - which isn't reachable by public.

Any Idea?

**Comment by bjendres** [comment]
>  I wan't to be sure that I can expect that civiproxy is still compatible with drupal9 / civicrm 7.60.

There shouldn't be any incompatibility with Drupal, but there might be issues with certain PHP versions - see the respective issues in this repository.

We don't have any information about compatibility with CivICRM 7.60 yet, so I think you should just try. I'm assuming these would also be raised as issues in here.

**Comment by bkaless** [comment]
After the update to Drupal 9/10 we had to change the endpoint:

``$target_rest      = $target_civicrm . '/civicrm/ajax/rest';

and you have to enable legacyrest authentication: [https://docs.civicrm.org/dev/en/latest/framework/authx/#flows](url)

We are using civiproxy in combination with CiviCRM in drupal 9.

**Comment by jankowa** [comment]
Thanks for the quick answer. I got a step further and can confirm that at least mailing/url etc. works. But I'm still stuggling with the rest api. @bkaless : can you give me a hint how and where to enable  the legacy rest authentication? I don't get a handle of the doc in this part.

**Comment by bkaless** [comment]
In /civicrm/admin/settings/authx you add "SiteKey" in the box "Authentication guard, HTTP-Header, HTTP-Parameter, HTTP X-Header, Legacy REST and Pipe".

In this discourse forum [https://community.software-fuer-engagierte.de/t/api-auf-drupal-9-extern-verfuegbar-machen/184](url) of "Software für Engagierte" you can find a german description @MarcMichalsky did to update our installation to drupal 9.

**Comment by jankowa** [comment]
Thanks a lot. I got it working. Good to know: the authx extension has to be installed.
