### ISSUE TITLE
Support Mosaico images

### ISSUE THREAD

**Issue by MegaphoneJon** [systopia/CiviProxy#7]
Mosaico stores its images in a different location from vanilla CiviMail.  I'll try to write a regex in `CRM_Civiproxy_Mailer::mendURLs()` to support it.

**Comment by systopia** [comment]
I'm not sure this is all that needs changing, the proxy itself might need some modifications too.

**Comment by PalanteJon** [comment]
Yes, of course!  I'm not ready to submit a PR yet because I need more testing, but I'm happy to say that I seem to have a working version here: https://github.com/PalanteJon/CiviProxy/tree/mosaico-support

**Comment by systopia** [comment]
released with ``0.5.beta1``
